services:
  frontend:
    container_name: wqam-frontend
    build:
      context: ./FRONTEND/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"      # host -> container nginx
    volumes:
      - ./FRONTEND/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always

  backend:
    container_name: wqam-backend
    build:
      context: ./BACKEND/backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 4000 --reload
    ports:
      - "4000:4000"
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: wqam
    restart: always
    depends_on:
      - timescaledb
      - redis
      - minio

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wqam
    ports:
      - "5432:5432"
    volumes:
      - tsdb_data:/home/postgres/pgdata/data

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"

volumes:
  tsdb_data:
  minio_data:
